apiVersion: v1
kind: Service
metadata:
  name: greetings-service-customer-svc
spec:
  selector:
    app: greetings-service-customer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
